export interface Env {
  UPSTREAM_BASE_URL: string;
  CF_ACCESS_CLIENT_ID: string;
  CF_ACCESS_CLIENT_SECRET: string;
}

const ALLOWED_PREFIXES = ["/v1/", "/health", "/docs", "/openapi.yaml"];

function isAllowedPath(pathname: string): boolean {
  return ALLOWED_PREFIXES.some((prefix) => pathname === prefix || pathname.startsWith(prefix));
}

function requiredEnv(name: keyof Env, env: Env): string {
  const value = env[name];
  if (!value || value.trim() === "") {
    throw new Error(`missing required env: ${name}`);
  }
  return value;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    try {
      const upstreamBase = requiredEnv("UPSTREAM_BASE_URL", env);
      const clientId = requiredEnv("CF_ACCESS_CLIENT_ID", env);
      const clientSecret = requiredEnv("CF_ACCESS_CLIENT_SECRET", env);

      const incomingURL = new URL(request.url);
      if (!isAllowedPath(incomingURL.pathname)) {
        return new Response("not found", { status: 404 });
      }

      const upstreamURL = new URL(incomingURL.pathname + incomingURL.search, upstreamBase);
      const headers = new Headers(request.headers);

      // Ensure Worker-controlled Cloudflare Access headers are always used.
      headers.delete("CF-Access-Client-Id");
      headers.delete("CF-Access-Client-Secret");
      headers.set("CF-Access-Client-Id", clientId);
      headers.set("CF-Access-Client-Secret", clientSecret);

      // Host header should be generated by fetch for the target host.
      headers.delete("Host");

      const init: RequestInit = {
        method: request.method,
        headers,
        redirect: "follow",
      };

      if (request.method !== "GET" && request.method !== "HEAD") {
        init.body = request.body;
      }

      return await fetch(upstreamURL.toString(), init);
    } catch (err) {
      const msg = err instanceof Error ? err.message : "proxy error";
      return new Response(JSON.stringify({ error: msg }), {
        status: 500,
        headers: { "Content-Type": "application/json" },
      });
    }
  },
};
